name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.10.31
      - cloudpickle==1.6.0
      - git+https://github.com/oishi-poddar/nyc_airbnb.git#egg=wandb-utils&subdirectory=components
